function gt = read_MOT20(filename, dataLines)
    %IMPORTFILE1 Import data from a text file
    %  GT = IMPORTFILE1(FILENAME) reads data from text file FILENAME for the
    %  default selection.  Returns the numeric data.
    %
    %  GT = IMPORTFILE1(FILE, DATALINES) reads data for the specified row
    %  interval(s) of text file FILENAME. Specify DATALINES as a positive
    %  scalar integer or a N-by-2 array of positive scalar integers for
    %  dis-contiguous row intervals.
    %
    %  Example:
    %  gt = importfile1("D:\data\gt.txt", [1, Inf]);
    %
    %  See also READTABLE.
    %
    % Auto-generated by MATLAB on 30-Sep-2025 18:55:50

    %% Input handling

    % If dataLines is not specified, define defaults
    if nargin < 2
        dataLines = [1, Inf];
    end

    %% Setup the Import Options
    opts = delimitedTextImportOptions("NumVariables", 9);

    % Specify range and delimiter
    opts.DataLines = dataLines;
    opts.Delimiter = ",";

    % Specify column names and types
    opts.VariableNames = ["VarName1", "VarName2", "VarName3", "VarName4", "VarName5", "VarName6", "Var7", "Var8", "Var9"];
    opts.SelectedVariableNames = ["VarName1", "VarName2", "VarName3", "VarName4", "VarName5", "VarName6"];
    opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "string", "string", "string"];
    opts = setvaropts(opts, [7, 8, 9], "WhitespaceRule", "preserve");
    opts = setvaropts(opts, [1, 2, 3, 4, 5, 6], "DecimalSeparator", ",");
    opts = setvaropts(opts, [7, 8, 9], "EmptyFieldRule", "auto");
    opts.ExtraColumnsRule = "ignore";
    opts.EmptyLineRule = "read";

    % Import the data
    gt = readtable(filename, opts);

    %% Convert to output type
    gt = table2array(gt);
    
    gt = sortrows(gt,[1,2]);
    
end