function [iq_filename, sample_rate, frame_number, frame_id, start_times, frame_lengths] = import_analysis_file(data_filename, data_lines)
    %IMPORTFILE Import data from a text file
    %  [FRAMENUMBER, FRAMEID, STARTTIMES, FRAMELENGTHS] =
    %  IMPORTFILE(FILENAME) reads data from text file FILENAME for the
    %  default selection.  Returns the data as column vectors.
    %
    %  [FRAMENUMBER, FRAMEID, STARTTIMES, FRAMELENGTHS] = IMPORTFILE(FILE,
    %  DATALINES) reads data for the specified row interval(s) of text file
    %  FILENAME. Specify DATALINES as a positive scalar integer or a N-by-2
    %  array of positive scalar integers for dis-contiguous row intervals.
    %
    %  Example:
    %  [frameNumber, frameID, StartTimes, frameLengths] = importfile("D:\Projects\data\RF\20240720\rb_times_v1.csv", [5, Inf]);
    %
    %  See also READTABLE.
    %
    % Auto-generated by MATLAB on 17-May-2025 10:01:32
    
    %% Input handling
    
    % If dataLines is not specified, define defaults
    if nargin < 2
        data_lines = [5, Inf];
    end

    %% read in the filename
    filename_opts = delimitedTextImportOptions("NumVariables", 1, "Encoding", "UTF-8");
    
    % Specify range and delimiter
    filename_opts.DataLines = [1, 1];

    rbtimesv1 = readmatrix(data_filename, filename_opts);

    iq_filename = rbtimesv1{1};

    %% read in the sample_rate
    sr_opts = delimitedTextImportOptions("NumVariables", 1, "Encoding", "UTF-8");

    % Specify range and delimiter
    sr_opts.DataLines = [2, 2];
    sr_opts.VariableTypes = ["double"];

    tbl = readtable(data_filename, sr_opts);
    sample_rate = tbl.Var1;
    
    %% Set up the Import Options and import the data
    data_opts = delimitedTextImportOptions("NumVariables", 4, "Encoding", "UTF-8");
    
    % Specify range and delimiter
    data_opts.DataLines = data_lines;
    data_opts.Delimiter = ",";
    
    % Specify column names and types
    data_opts.VariableNames = ["frameNumber", "frameID", "StartTimes", "frameLengths"];
    data_opts.VariableTypes = ["double", "double", "double", "double"];
    
    % Specify file level properties
    data_opts.ExtraColumnsRule = "ignore";
    data_opts.EmptyLineRule = "read";
    
    % Import the data
    tbl = readtable(data_filename, data_opts);
    tbl = table2array(tbl);

    % remove NANs
    tbl = tbl(sum(isnan(tbl),2)==0, :);
    
    %% Convert to output type
    % frame_number = tbl.frameNumber;
    % frame_id = tbl.frameID;
    % start_times = tbl.StartTimes;
    % frame_lengths = tbl.frameLengths;
    frame_number = tbl(:, 1);
    frame_id = tbl(:, 2);
    start_times = tbl(:, 3);
    frame_lengths = tbl(:, 4);

end