function [param_type, file_index] = file_params_dialog
    
    param_type = 'Normal';
    file_index = 1;
    
    d = dialog('Position',[300 300 250 100],'Name','File Params Dialog');

    txt1 = uicontrol('Parent',d,...
            'Style','text',...
            'Position',[10 50 130 40],...
            'String','Select the input file type:');

    popup = uicontrol('Parent',d,...
            'Style','popup',...
            'Position',[140 68 80 25],...
            'String',{'Normal';'Grouped'},...
            'Callback',@popup_callback);
        
    txt2 = uicontrol('Parent',d,...
            'Style','text',...
            'Position',[45 20 130 40],...
            'String','File Index:');
        
    fidx = uicontrol('Parent',d,...
            'Style','edit',...
            'Position',[140 40 50 23],...
            'String','1',...
            'Callback',@fidx_callback);
           
    btn = uicontrol('Parent',d,...
            'Position',[85 10 70 25],...
            'String','Run',...
            'Callback','delete(gcf)');
           
    uiwait(d);

    function popup_callback(popup, event)
        idx = popup.Value;
        popup_items = popup.String;

        param_type = char(popup_items(idx,:));
    end  

    function fidx_callback(fidx, event)
        file_index = str2double(fidx.String);
    end

end