% Create a horn antenna
% Generated by MATLAB(R) 9.6 and Antenna Toolbox 4.0.
% Generated on: 25-Feb-2024 13:07:21
function [g] = conical_horn_objective(X)
    
    design_frequency = 9350000000;
    
    % Antenna Properties 
    antennaObject = design(hornConical, design_frequency);
    
    try
        antennaObject.Radius = X(1);
        antennaObject.WaveguideHeight = X(2);
        antennaObject.FeedHeight = X(3);
        antennaObject.FeedWidth = X(4);
        antennaObject.FeedOffset = X(5);
        antennaObject.ConeHeight = X(6);
        antennaObject.ApertureRadius = X(7);
        antennaObject.Conductor.Conductivity = 5.8*1e7;
        antennaObject.Conductor.Thickness = 0.000127;

        % Antenna Analysis    
        g = -patternAzimuth(antennaObject, design_frequency, 0, 'Azimuth', 270);
    catch ME
        g = 1e6;
        % warning('Problem with antenna parameters...');
        disp(ME.message);
    end

end
