% Create a horn antenna
% Generated by MATLAB(R) 9.6 and Antenna Toolbox 4.0.
% Generated on: 25-Feb-2024 13:07:21
function [g] = horn_objective(X)
    
    design_frequency = 9350000000;
    
    % Antenna Properties 
    antennaObject = design(horn, design_frequency);
    
    try
        antennaObject.FeedWidth = X(1);
        antennaObject.FeedHeight = X(2);
        antennaObject.Height = X(3);
        antennaObject.Width = X(4);
        antennaObject.Length = X(5);
        antennaObject.FlareLength = X(6);
        antennaObject.FlareHeight = X(7);
        antennaObject.FlareWidth = X(8);
        antennaObject.FeedOffset = [X(9) 0];

        % Antenna Analysis    
        g = -patternAzimuth(antennaObject, design_frequency, 0, 'Azimuth', 0);
    catch ME
        g = 1e6;
        warning('Problem with antenna parameters...');
        disp(ME.message);
    end

end
